from uvispace.uvisensor.uvisensor import UviSensor

if __name__ == '__main__':
    """
    Just launches the UviSensor package and starts streaming images and
    triangles. Call with: python -m uvispace.uvisensors
    Use UviGui or tests/test_uvisensor.py to see the
    multiframe image generated by UviSensor.
    """
    # start the stream of multi-images throug zmq socket
    sensor = UviSensor(enable_img = True, enable_triang = False, threaded = False)
    sensor.start_stream()
