import cv2
import time
import sys
import configparser
import zmq
import numpy as np

from uvispace.uvisensor.uvisensor import UviSensor

if __name__ == '__main__':
    """
    Just launches the Uvispace package and starts streaming images and
    triangles. Call with: python -m uvispace.uvisensor
    Use UviGui or tests/test_uvisensor.py to see the
    multiframe image generated by UviSensor.
    """
    # start the stream of multi-images throug zmq socket
    sensor = UviSensor(enable_img = True, enable_triang = False)
    sensor.start_stream()
