# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'neural_controller_trainer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fuzzy_window(object):
    def setupUi(self, fuzzy_window):
        fuzzy_window.setObjectName("fuzzy_window")
        fuzzy_window.resize(721, 552)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fuzzy_window.sizePolicy().hasHeightForWidth())
        fuzzy_window.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(fuzzy_window)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_0)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.page_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.rbNeural = QtWidgets.QRadioButton(self.page_0)
        self.rbNeural.setAutoFillBackground(False)
        self.rbNeural.setChecked(True)
        self.rbNeural.setObjectName("rbNeural")
        self.rbModelGroup = QtWidgets.QButtonGroup(fuzzy_window)
        self.rbModelGroup.setObjectName("rbModelGroup")
        self.rbModelGroup.addButton(self.rbNeural)
        self.horizontalLayout.addWidget(self.rbNeural)
        self.rbTables = QtWidgets.QRadioButton(self.page_0)
        self.rbTables.setObjectName("rbTables")
        self.rbModelGroup.addButton(self.rbTables)
        self.horizontalLayout.addWidget(self.rbTables)
        self.pbStartTraining = QtWidgets.QPushButton(self.page_0)
        self.pbStartTraining.setObjectName("pbStartTraining")
        self.horizontalLayout.addWidget(self.pbStartTraining)
        self.pbAnnFile = QtWidgets.QPushButton(self.page_0)
        self.pbAnnFile.setObjectName("pbAnnFile")
        self.horizontalLayout.addWidget(self.pbAnnFile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbStartTesting = QtWidgets.QPushButton(self.page_0)
        self.pbStartTesting.setObjectName("pbStartTesting")
        self.horizontalLayout.addWidget(self.pbStartTesting)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lModel = QtWidgets.QLabel(self.page_0)
        self.lModel.setObjectName("lModel")
        self.horizontalLayout_4.addWidget(self.lModel)
        self.rbDifferential = QtWidgets.QRadioButton(self.page_0)
        self.rbDifferential.setChecked(True)
        self.rbDifferential.setObjectName("rbDifferential")
        self.rbControllerGroup = QtWidgets.QButtonGroup(fuzzy_window)
        self.rbControllerGroup.setObjectName("rbControllerGroup")
        self.rbControllerGroup.addButton(self.rbDifferential)
        self.horizontalLayout_4.addWidget(self.rbDifferential)
        self.rbAckerman = QtWidgets.QRadioButton(self.page_0)
        self.rbAckerman.setObjectName("rbAckerman")
        self.rbControllerGroup.addButton(self.rbAckerman)
        self.horizontalLayout_4.addWidget(self.rbAckerman)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_plot = QtWidgets.QVBoxLayout()
        self.verticalLayout_plot.setSpacing(6)
        self.verticalLayout_plot.setObjectName("verticalLayout_plot")
        self.verticalLayout.addLayout(self.verticalLayout_plot)
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pbRetrain = QtWidgets.QPushButton(self.page_1)
        self.pbRetrain.setObjectName("pbRetrain")
        self.horizontalLayout_3.addWidget(self.pbRetrain)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_plot_test = QtWidgets.QGridLayout()
        self.gridLayout_plot_test.setSpacing(6)
        self.gridLayout_plot_test.setObjectName("gridLayout_plot_test")
        self.horizontalLayout_9.addLayout(self.gridLayout_plot_test)
        self.gridLayout_plot_sim = QtWidgets.QGridLayout()
        self.gridLayout_plot_sim.setSpacing(6)
        self.gridLayout_plot_sim.setObjectName("gridLayout_plot_sim")
        self.horizontalLayout_9.addLayout(self.gridLayout_plot_sim)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.stackedWidget.addWidget(self.page_1)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        fuzzy_window.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(fuzzy_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 721, 26))
        self.menuBar.setObjectName("menuBar")
        fuzzy_window.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(fuzzy_window)
        self.mainToolBar.setObjectName("mainToolBar")
        fuzzy_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(fuzzy_window)
        self.statusBar.setObjectName("statusBar")
        fuzzy_window.setStatusBar(self.statusBar)

        self.retranslateUi(fuzzy_window)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fuzzy_window)

    def retranslateUi(self, fuzzy_window):
        _translate = QtCore.QCoreApplication.translate
        fuzzy_window.setWindowTitle(_translate("fuzzy_window", "proba"))
        self.label_3.setText(_translate("fuzzy_window", "Choose the controller:"))
        self.rbNeural.setText(_translate("fuzzy_window", "Neural Network"))
        self.rbTables.setText(_translate("fuzzy_window", "Tables"))
        self.pbStartTraining.setText(_translate("fuzzy_window", "Start Training"))
        self.pbAnnFile.setText(_translate("fuzzy_window", "ANN file"))
        self.pbStartTesting.setText(_translate("fuzzy_window", "Start Testing"))
        self.lModel.setText(_translate("fuzzy_window", "Choose vehicle model:"))
        self.rbDifferential.setText(_translate("fuzzy_window", "Differential"))
        self.rbAckerman.setText(_translate("fuzzy_window", "Ackerman"))
        self.label_2.setText(_translate("fuzzy_window", "Testing"))
        self.pbRetrain.setText(_translate("fuzzy_window", "Re-Train"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fuzzy_window = QtWidgets.QMainWindow()
    ui = Ui_fuzzy_window()
    ui.setupUi(fuzzy_window)
    fuzzy_window.show()
    sys.exit(app.exec_())

