# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_interface.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_proba(object):
    def setupUi(self, proba):
        proba.setObjectName("proba")
        proba.resize(638, 418)
        self.centralWidget = QtWidgets.QWidget(proba)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.next0Button = QtWidgets.QPushButton(self.page_0)
        self.next0Button.setGeometry(QtCore.QRect(530, 320, 75, 23))
        self.next0Button.setObjectName("next0Button")
        self.label = QtWidgets.QLabel(self.page_0)
        self.label.setGeometry(QtCore.QRect(10, 0, 61, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page_0)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 321, 71))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_2 = QtWidgets.QLabel(self.page_1)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 47, 13))
        self.label_2.setObjectName("label_2")
        self.next1Button = QtWidgets.QPushButton(self.page_1)
        self.next1Button.setGeometry(QtCore.QRect(540, 320, 75, 23))
        self.next1Button.setObjectName("next1Button")
        self.prev1Button = QtWidgets.QPushButton(self.page_1)
        self.prev1Button.setGeometry(QtCore.QRect(0, 320, 75, 23))
        self.prev1Button.setObjectName("prev1Button")
        self.label_4 = QtWidgets.QLabel(self.page_1)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_1)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 211, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_6.setObjectName("label_6")
        self.next2Button = QtWidgets.QPushButton(self.page_2)
        self.next2Button.setGeometry(QtCore.QRect(540, 320, 75, 23))
        self.next2Button.setObjectName("next2Button")
        self.prev2Button = QtWidgets.QPushButton(self.page_2)
        self.prev2Button.setGeometry(QtCore.QRect(0, 320, 75, 23))
        self.prev2Button.setObjectName("prev2Button")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 211, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_ready = QtWidgets.QLabel(self.page_2)
        self.label_ready.setGeometry(QtCore.QRect(420, 280, 171, 16))
        self.label_ready.setObjectName("label_ready")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 320, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.prev4Button = QtWidgets.QPushButton(self.page_3)
        self.prev4Button.setGeometry(QtCore.QRect(530, 320, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev4Button.sizePolicy().hasHeightForWidth())
        self.prev4Button.setSizePolicy(sizePolicy)
        self.prev4Button.setObjectName("prev4Button")
        self.next4Button = QtWidgets.QPushButton(self.page_3)
        self.next4Button.setGeometry(QtCore.QRect(0, 320, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next4Button.sizePolicy().hasHeightForWidth())
        self.next4Button.setSizePolicy(sizePolicy)
        self.next4Button.setObjectName("next4Button")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(140, 320, 191, 21))
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        proba.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(proba)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 638, 21))
        self.menuBar.setObjectName("menuBar")
        proba.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(proba)
        self.mainToolBar.setObjectName("mainToolBar")
        proba.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(proba)
        self.statusBar.setObjectName("statusBar")
        proba.setStatusBar(self.statusBar)

        self.retranslateUi(proba)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(proba)

    def retranslateUi(self, proba):
        _translate = QtCore.QCoreApplication.translate
        proba.setWindowTitle(_translate("proba", "proba"))
        self.next0Button.setText(_translate("proba", "Next Step"))
        self.label.setText(_translate("proba", "Step 1"))
        self.label_3.setText(_translate("proba", "Put the vehicle on the central position of the camera number 1"))
        self.label_2.setText(_translate("proba", "Step 2"))
        self.next1Button.setText(_translate("proba", "Next Step"))
        self.prev1Button.setText(_translate("proba", "Previous Step"))
        self.label_4.setText(_translate("proba", "Connect the vehicle using the power cord"))
        self.label_5.setText(_translate("proba", "Set the power source to 10 V 3A Vcc"))
        self.label_6.setText(_translate("proba", "Step 3"))
        self.next2Button.setText(_translate("proba", "Next Step"))
        self.prev2Button.setText(_translate("proba", "Previous Step"))
        self.label_7.setText(_translate("proba", "Do you want to start the calibration process?"))
        self.label_10.setText(_translate("proba", "The vehicle is going to do some movements"))
        self.pushButton.setText(_translate("proba", "Start"))
        self.label_ready.setText(_translate("proba", "Calibration finished. Click on next"))
        self.label_8.setText(_translate("proba", "Stage 4"))
        self.label_9.setText(_translate("proba", "Calibration results"))
        self.pushButton_2.setText(_translate("proba", "Repeat"))
        self.prev4Button.setText(_translate("proba", "Previous Step"))
        self.next4Button.setText(_translate("proba", "Finish test"))
        self.label_11.setText(_translate("proba", "Do you want to repeat the calibration?"))

